server:
  port: 8080

spring:
  jackson: # 返回JSON的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/demodb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    database: 0
#    host: 39.96.49.72
#    lettuce:
#      pool:
#        max-active: 20
#        max-idle: 5
#        max-wait: -1
#        min-idle: 0
#    port: 6379
#    timeout: 1800000

#mybatis -plus的配置，可以将日志输出
mybatis-plus:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:com/springboot/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #    global-Webconfig:
  #      db-Webconfig:
  #        id-type: auto

  #      map-underscore-to-camel-case: true
  #xxlJob
  ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
  #  xxl.job.admin.addresses=http://xxl-job:8080/xxl-job-admin/
  ### 执行器通讯TOKEN [选填]：非空时启用；
  #  xxl.job.admin.accessToken=
  ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
  #  xxl.job.admin.appname= fantasyci-xxl-job
  ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
  #  xxl.job.admin.ip=
  ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
  #  xxl.job.admin.port=9999
  ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
  #  xxl.job.admin.logpath=root/logs/xxl-job/jobhandler
  ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#  xxl.job.admin.logretentiondays=30
#xxl:
#  job:
#    admin:
#      addresses: http://xxl-job:8080/xxl-job-admin/
#      accessToken:
#      appname: fantasyci-xxl-job
#      ip: ''
#      port: 9999
#      logpath: root/logs/xxl-job/jobhandler
#      logretentiondays: 30
#日志设置
#logging:
#  config: classpath:logback-spring.xml
#  level:
#    root: INfO
