server:
  port: 8099

#数据库 配置
spring:
  #  mysql 数据源
  datasource:
    # 数据库引擎，最新的数据库都需要加入cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus_db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 DruidDataSource作为数据源
#    h2 数据库数据源
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: root
#    password: test
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql


# MyBatis-plus配置
mybatis-plus:
  # xml文件位置
  mapper-locations: classpath*:mapper/*.xml
  # 别名类型包
  type-aliases-package: com.xiaomi.mybatisplus.entity
  global-config:
    banner: false   # 是否 mybatis-plus 在控制台输出的logo
    db-config:
      # 全局逻辑删除的字段名
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 主键 自增
      id-type: auto
  configuration:
    # 开启驼峰转换
    map-underscore-to-camel-case: true
    # MyBatis日志打印类
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl   # 关闭日志
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl         # 打印到控制台
    auto-mapping-behavior: full
